name: Build Fat JAR

on:
  workflow_call: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
      - run: ./gradlew buildFatJar
      - name: Upload Fat JAR
        uses: actions/upload-artifact@v4
        with:
          name: fat-jar
          path: build/libs/*.jar
