name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up the SSH key
      - name: Set up SSH Key
        run: |
          echo "Setting up SSH key..."
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Adding VPS host key to known_hosts..."
          ssh-keyscan -H -p 22 ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          echo "SSH key setup complete."

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 2: Debug SSH Key Permissions and Content
      - name: Debug SSH Key and Permissions
        run: |
          echo "Checking permissions and contents..."
          ls -lah ~/.ssh
          echo "Private key starts with:"
          head -n 3 ~/.ssh/id_rsa
          echo "Private key ends with:"
          tail -n 3 ~/.ssh/id_rsa

      # Step 3: Attempt SSH Connection with Verbose Output
      - name: Test SSH Connection with Debug Info
        run: |
          echo "Testing SSH connection..."
          ssh -vvv -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo 'Connection successful!'"

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
